premium.settings:
  type: mapping
  label: Settings
  mapping:
    premium_mode:
      type: integer
    premium_time_count:
      type: integer
    premium_time_unit:
      type: string
    premium_message:
      type: string
    premium_format:
      type: string
