buttons_size: 30
additional_html: "<a class=\"a2a_button_linkedin\" aria-label=\"LinkedIn\"><i class=\"fab fa-linkedin\"></i><span aria-hidden=\"true\" style=\"display:none\">Share on LinkedIn</span></a>\r\n<a class=\"a2a_button_twitter\" aria-label=\"Twitter\"><i class=\"fab fa-twitter\"></i><span aria-hidden=\"true\" style=\"display:none\">Share on Twitter</span></a>\r\n<a class=\"a2a_button_facebook\" aria-label=\"Facebook\"><i class=\"fab fa-facebook-f\"></i><span aria-hidden=\"true\" style=\"display:none\">Facebook</span></a>"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
no_3p: false
entities:
  media: 0
  node: 1
  comment: 0
  block_content: 0
  contact_message: 0
  content_moderation_state: 0
  crop: 0
  feeds_subscription: 0
  feeds_feed: 0
  file: 0
  gathercontent_operation_item: 0
  gathercontent_operation: 0
  paragraphs_library_item: 0
  path_alias: 0
  redirect: 0
  search_api_task: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  menu_link_content: 0
  paragraph: 0
_core:
  default_config_hash: '-oeXHVXl-m1HE6XR_-FXfNgJOgPuHcOCWSkymfOR7Sc'
