definitions:
  contact__site_page:
    weight: -39
    menu_name: footer
    parent: ''
    expanded: false
    enabled: false
  standard__front_page:
    weight: -45
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  help__main:
    weight: -91
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:view__files':
    weight: 2
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: false
  system__admin_content:
    weight: -98
    menu_name: admin
    parent: system.admin
    enabled: true
    expanded: false
  system__admin_structure:
    weight: -97
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__themes_page:
    weight: -96
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__modules_list:
    weight: -95
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_config:
    weight: -94
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  entity__user__collection:
    weight: -93
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  system__admin_reports:
    weight: -92
    menu_name: admin
    parent: system.admin
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media_page':
    weight: 4
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__audio':
    weight: 1
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__campus_directory_headshots':
    weight: 2
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__curriculum_vitae':
    weight: 3
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__document':
    weight: 5
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__header_image':
    weight: 6
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__image':
    weight: 7
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__remote_video':
    weight: 8
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  'admin_toolbar_tools__extra_links:media__add__video':
    weight: 9
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:add_media'
    expanded: false
    enabled: true
  paragraphs_library__paragraphs_library_item__collection:
    weight: 5
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
