module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  anchor_link: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  bulk_edit_terms: 0
  cas: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  crop: 0
  csv_importer: 0
  ctools: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  diff: 0
  domain: 0
  domain_alias: 0
  domain_config: 0
  domain_source: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  emergency_alerts: 0
  entity_clone: 0
  entity_reference_revisions: 0
  entity_usage: 0
  event_log_track: 0
  event_log_track_auth: 0
  event_log_track_file: 0
  event_log_track_menu: 0
  event_log_track_node: 0
  event_log_track_taxonomy: 0
  event_log_track_user: 0
  event_log_track_workflows: 0
  fakeobjects: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flood_unblock: 0
  gathercontent: 0
  google_analytics: 0
  google_cse: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  imageapi_optimize: 0
  imageapi_optimize_resmushit: 0
  imce: 0
  language: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_attributes: 0
  linkit: 0
  ludwig: 0
  mailsystem: 0
  masquerade: 0
  menu_block: 0
  menu_breadcrumb: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  node_type_count: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  redirect_after_login: 0
  redirect_domain: 0
  redis: 0
  rules: 0
  scanner: 0
  search: 0
  search_api: 0
  search_api_db: 0
  sendgrid_integration: 0
  shortcut: 0
  shs: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  simple_sitemap_views: 0
  simpscar_admin_theme_overrides: 0
  superfish: 0
  syslog: 0
  system: 0
  tac_lite_create: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  term_csv_export_import: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  u_pacific_feeds: 0
  update: 0
  user: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_show_more: 0
  views_ui: 0
  workflows: 0
  yoast_seo: 0
  youtube: 0
  menu_link_content: 1
  pathauto: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  tac_lite: 100
  standard: 1000
theme:
  stable: 0
  classy: 0
  claro: 0
  u_pacific: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
