gathercontent_username: rhess@pacific.edu
gathercontent_api_key: 733b880b-750c-432c-87bf-5dfb3370c3b6
gathercontent_account: 'a:1:{i:48804;s:25:"University of the Pacific";}'
_core:
  default_config_hash: '-JuP8QoLVzx3zl3_It53MeR6QmysWOtaJ3xoDn9S5EA'
gathercontent_urlkey: universityofthepacific
