scanner_mode: false
scanner_wholeword: false
scanner_regex: false
scanner_published: false
scanner_pathauto: false
scanner_language: all
enabled_content_types:
  'paragraph:accordion': 'paragraph:accordion'
  'paragraph:accordion_content': 'paragraph:accordion_content'
  'paragraph:advanced_acco': 'paragraph:advanced_acco'
  'paragraph:carousel': 'paragraph:carousel'
  'paragraph:content_accordions': 'paragraph:content_accordions'
  'paragraph:directory_listing': 'paragraph:directory_listing'
  'paragraph:from_library': 'paragraph:from_library'
  'paragraph:headline_call_to_action': 'paragraph:headline_call_to_action'
  'paragraph:image_button': 'paragraph:image_button'
  'paragraph:image_with_caption': 'paragraph:image_with_caption'
  'paragraph:large_image_callout': 'paragraph:large_image_callout'
  'paragraph:link': 'paragraph:link'
  'paragraph:link_list_2_columns_': 'paragraph:link_list_2_columns_'
  'paragraph:multi_colu_mn_text_grid': 'paragraph:multi_colu_mn_text_grid'
  'paragraph:nested_paragraph': 'paragraph:nested_paragraph'
  'paragraph:pulled_quote': 'paragraph:pulled_quote'
  'paragraph:rotator': 'paragraph:rotator'
  'paragraph:simple_wysiwyg': 'paragraph:simple_wysiwyg'
  'paragraph:slide': 'paragraph:slide'
  'paragraph:test_extended_2_col': 'paragraph:test_extended_2_col'
  'paragraph:text': 'paragraph:text'
  'paragraph:text_column': 'paragraph:text_column'
  'paragraph:title_text_links_3_columns_': 'paragraph:title_text_links_3_columns_'
  'paragraph:two_column_one_column_text_one_c': 'paragraph:two_column_one_column_text_one_c'
  'paragraph:video': 'paragraph:video'
  'paragraph:video_block': 'paragraph:video_block'
  'paragraph:yellow_links': 'paragraph:yellow_links'
  'node:article': 'node:article'
  'node:campus_directory': 'node:campus_directory'
  'node:college_school_landing_page': 'node:college_school_landing_page'
  'node:department_landing_pages': 'node:department_landing_pages'
  'node:landing_page': 'node:landing_page'
  'node:library': 'node:library'
  'node:major_pages': 'node:major_pages'
  'node:page': 'node:page'
fields_of_selected_content_type:
  'paragraph:accordion_content:field_text_field': 'paragraph:accordion_content:field_text_field'
  'paragraph:pulled_quote:field_quote': 'paragraph:pulled_quote:field_quote'
  'paragraph:rotator:field_text_field': 'paragraph:rotator:field_text_field'
  'paragraph:simple_wysiwyg:field_text_field': 'paragraph:simple_wysiwyg:field_text_field'
  'paragraph:slide:field_description': 'paragraph:slide:field_description'
  'paragraph:text:field_description': 'paragraph:text:field_description'
  'paragraph:text_column:field_description': 'paragraph:text_column:field_description'
  'paragraph:title_text_links_3_columns_:field_text_field': 'paragraph:title_text_links_3_columns_:field_text_field'
  'node:article:body': 'node:article:body'
  'node:article:field_external_url': 'node:article:field_external_url'
  'node:campus_directory:field_biography': 'node:campus_directory:field_biography'
  'node:campus_directory:field_education': 'node:campus_directory:field_education'
  'node:campus_directory:field_office_location': 'node:campus_directory:field_office_location'
  'node:campus_directory:field_office_location_2': 'node:campus_directory:field_office_location_2'
  'node:campus_directory:field_research_focus': 'node:campus_directory:field_research_focus'
  'node:campus_directory:field_teaching_interests': 'node:campus_directory:field_teaching_interests'
  'node:college_school_landing_page:body': 'node:college_school_landing_page:body'
  'node:college_school_landing_page:field_contact_location': 'node:college_school_landing_page:field_contact_location'
  'node:department_landing_pages:body': 'node:department_landing_pages:body'
  'node:department_landing_pages:field_additional_text': 'node:department_landing_pages:field_additional_text'
  'node:department_landing_pages:field_contact_location': 'node:department_landing_pages:field_contact_location'
  'node:landing_page:body': 'node:landing_page:body'
  'node:library:body': 'node:library:body'
  'node:major_pages:body': 'node:major_pages:body'
  'node:major_pages:field_contact_location': 'node:major_pages:field_contact_location'
  'node:major_pages:field_more_information': 'node:major_pages:field_more_information'
  'node:page:body': 'node:page:body'
_core:
  default_config_hash: m3e3lR0iNbau3eUO2RZya6iS06zv02m1JJe8X-PZuhk
