apikey: 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
test_defaults:
  to: bmccombs@simpsonscarborough.com
  subject: 'Test Email from SendGrid Module'
  body:
    value: "<p>Test Message for SendGrid.</p>\r\n"
    format: full_html
  from_name: Drupal
  to_name: 'Tony Carrero'
  reply_to: ''
_core:
  default_config_hash: g4qz7cPnloXFwtnLYfIKI2VS0gf_UFOz_I2uQiiulC8
